### ISSUE TITLE
Could not find a version that satisfies the requirement nbashots

### ISSUE THREAD

**Issue by qualitydixon** [savvastj/nbashots#1]
Having trouble installing. `pip list` shows I have all the correct dependencies installed but when I try `pip install nbashots` I get the following error:

_Downloading/unpacking nbashots
  Could not find a version that satisfies the requirement nbashots (from versions: 0.1.0a8, 0.1.0a9)
Cleaning up...
No distributions matching the version for nbashots
Storing debug log for failure in /home/mike/.pip/pip.log_

I'm not that familiar with pip/python so I'm guessing this is not so much an issue as it is my error. I appreciate any help!

**Comment by savvastj** [comment]
Try running `pip install --pre nbashots`. Let me know if it works or if you run into the same issue again.

**Comment by qualitydixon** [comment]
Yes that fixed it! Thanks for the response.

**Comment by savvastj** [comment]
Np, glad it worked!
